### ISSUE TITLE
Admob banner priority over keyboard

### ISSUE THREAD

**Issue by edips** [Larpon/QtFirebase#67]
Hi. When keyboard is activated admob banner is still on. How can I hide it behind keyboard? Thanks!
Screenshot: https://ibb.co/nu5NPw

**Comment by Larpon** [comment]
@edips - this is by design.
Google ensures the visibility of their ads can be trusted and not "fiddled with" so I assume they are in some overlay above Qt's scene.

I suggest you put some logic in your input item's `onActiveFocusChanged` or similar and handle the ad visibility yourself
```
TextInput {
      onActiveFocusChanged: { adbanner.visible = !activeFocus }
}
```
This will lead to a more complex handling, yes, but I can't think of anything else right now.
Hope it helps!

**Comment by edips** [comment]
İ searched about it at stack overflow , in order to prevent this its solution was to add  windowSoftInputMode = "adjustPan" to activity tag of manifest file. But it didn't work. When I add I add the banner top of screen it closes application window pane. I would like to insert the banner top of the application window. İt is not possible to anchor application window but I will try another methods. Else I will try your suggestion that when keyboard is active ad banner is off.Thanks for suggestion.

**Comment by Larpon** [comment]
Yeah - you could move it to top with `moveTo` like [here](https://github.com/Larpon/QtFirebaseExample/blob/4ba5d1041a27c2175c17094b5aa4550ad5d0d964/App/main.qml#L241)

**Comment by edips** [comment]
I found out a solution when the banner is below. Thanks.
`visible:Qt.inputMethod.visible ? false : loaded && !loader.ready`
